"""add column files process

Revision ID: bd54aa8ce1ee
Revises: a2c648c77b33
Create Date: 2025-11-26 18:00:30.073503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd54aa8ce1ee'
down_revision: Union[str, Sequence[str], None] = 'a2c648c77b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('processed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('files', sa.Column('processing_status', sa.String(length=20), server_default='pending', nullable=False))
    op.add_column('files', sa.Column('thumbnail_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'thumbnail_path')
    op.drop_column('files', 'processing_status')
    op.drop_column('files', 'processed')
    # ### end Alembic commands ###
